[project]
name = "fails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.73.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "weave>=0.51.54",
]
