[project]
name = "fails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # Core dependencies
    "litellm>=1.73.1",
    "openai-agents[litellm]>=0.0.19",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "simple-parsing>=0.1.7",
    "weave>=0.51.54",
    # ML dependencies for sophisticated scorers - exact versions that work together
    "scikit-learn==1.5.2",
    "sentence-transformers==2.7.0",
    "numpy==1.26.4",
    "torch==2.4.1",
    "transformers==4.44.2",
    "tensorflow==2.17.0",
    "huggingface-hub==0.24.6",
    "tokenizers==0.19.1",
    "safetensors==0.4.4",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fails"]
