wandb-applied-ai-team/eval-failures:
  failure_column: output.scores.affiliation_score.correct
  failure_value: false
  failure_categorization_columns:
  - inputs.example.affiliation
  - inputs.example.call_name
  - inputs.example.full_transcript
  - output.scores.affiliation_score.correct
  - exception
  - output.scores.affiliation_score
  - output.output.reasoning
  - output.output.affiliation
